/* eslint-disable no-unused-vars */
export enum RokuRemoteKey {
  BACK = 'Back',
  BACKSPACE = 'Backspace',
  CHANNEL_DOWN = 'ChannelDown',
  CHANNEL_UP = 'ChannelUp',
  DOWN = 'Down',
  ENTER = 'Enter',
  FIND_REMOTE = 'FindRemote',
  FWD = 'Fwd',
  HOME = 'Home',
  INFO = 'Info',
  INPUT_AV1 = 'InputAV1',
  INPUT_HDMI1 = 'InputHDMI1',
  INPUT_HDMI2 = 'InputHDMI2',
  INPUT_HDMI3 = 'InputHDMI3',
  INPUT_HDMI4 = 'InputHDMI4',
  INPUT_TUNER = 'InputTuner',
  INSTANT_REPLAY = 'InstantReplay',
  LEFT = 'Left',
  ONSCREEN_KEYBOARD = 'Lit_',
  PLAY = 'Play',
  POWER_OFF = 'PowerOff',
  REV = 'Rev',
  RIGHT = 'Right',
  SEARCH = 'Search',
  SELECT = 'Select',
  UP = 'Up',
  VOLUME_DOWN = 'VolumeDown',
  VOLUME_MUTE = 'VolumeMute',
  VOLUME_UP = 'VolumeUp',
}
/* eslint-enable no-unused-vars */
